name: "edge"
services:
  core:
    build:
      context: .
      args:
        - DOCKER_UID=${UID:-1000}
        - DOCKER_GID=${GID:-1000}
        - DOCKER_USER=portal
        - DOCKER_GROUP=portal
    working_dir: /home/portal/workspace
    volumes:
      - type: bind
        source: .
        target: /home/portal/workspace
        consistency: cached
      - type: volume
        source: node-volume
        target: /home/portal/workspace/node_modules
        volume:
          nocopy: true
      - type: volume
        source: bun-volume
        target: /home/portal/.bun
        volume:
          nocopy: true
    expose:
      - '5170'
      - '5171'
      - '5172'
      - '5173'
    command: sleep infinity
    tty: true
    stdin_open: true
    init: true
    user: portal:portal
    environment:
      - NODE_OPTIONS=--max-old-space-size=4096
    restart: unless-stopped
volumes:
  bun-volume:
    driver: local
  node-volume:
    driver: local
  
